### ISSUE TITLE
Pipeline not following naming convention and logo missing

### ISSUE THREAD

**Issue by sven1103** [nf-core/ICGC-featureCounts#8]
no camelcase,
no hyphen, 
all small letters.

for example: `featurecountsicgc` or `featurecounts` only?

**Comment by maxulysse** [comment]
I vote for `featurecounts`.
I think that in the long term it should work on more than ICGC

**Comment by maxulysse** [comment]
Why not `featurecountsonaws` cf #7 ?

**Comment by silverslott** [comment]
same thing with EAGER2? :-)

**Comment by maxulysse** [comment]
And ViPR

**Comment by ewels** [comment]
Yes - the reasoning for this is that simple lower case names will then be identical as dockerhub image (which _has_ to have those constraints).

**Comment by maxulysse** [comment]
We could have a `toLowerCase` and strip `-` for Docker and just `toLowerCase` for Singularity.
But yes, I can see see why you would want such requirements.

**Comment by apeltzer** [comment]
I think I’ll go for plain featurecounts and plain eager then - can make the intention of each pipeline clear in all cases anyways in the introduction and in the docs.

**Comment by apeltzer** [comment]
Logo is there, will still keep the nf-core one if thats ok? 
I made it lowercase and kept the icgc, removed all profiles other than AWSBatch though to make clear this can only be used there.
